### ISSUE TITLE
Doubts about iPhone 14 Results

### ISSUE THREAD

**Issue by WYHZQ** [zhangzjn/EMO#10]
According to NextViT's[1] report, on iPhone 12, models with much larger parameter quantities such as ResNet101 and NextViT-S have a delay of only about 4ms compared to EMO. The delay of EfficientFormer-L1[2] with a parameter quantity of 12M is only 1.6ms. The hardware of iPhone 14 is stronger than iPhone 12, and the latency of smaller EMO should be lower. However, the delay of EMO family is over 4ms. What is the reason for this?

[1] Li J, Xia X, Li W, et al. Next-vit: Next generation vision transformer for efficient deployment in realistic industrial scenarios[J]. arXiv preprint arXiv:2207.05501, 2022.
[2] Li Y, Yuan G, Wen Y, et al. Efficientformer: Vision transformers at mobilenet speed[J]. Advances in Neural Information Processing Systems, 2022, 35: 12934-12949.

**Comment by zhangzjn** [comment]
Sorry for the late response. We follow the official [classification project](https://developer.apple.com/documentation/vision/classifying_images_with_vision_and_core_ml) which is a more practical application scenario that could involve data loading and processing with batch size 1. This should be the reason for the gap. 

Please refer to [model/_emo_ios.py](https://github.com/zhangzjn/EMO/blob/main/model/_emo_ios.py) for producing relevant *IOS* models.
