### ISSUE TITLE
debug.py

### ISSUE THREAD

**Issue by waangyuhai** [zhangzjn/EMO#11]
请问一下这个debug.py文件为啥项目中没有

**Comment by zhangzjn** [comment]
You can modify `configs/debug.py` to `configs/mobile/cls_emo.py` in [run.py](run.py) for debugging. The `debug` file changes only a few parameters for ease of debugging, *e.g.*, batch size, scheduler, DDP, *etc*.

**Comment by waangyuhai** [comment]
Received, thanks for your reply
