### ISSUE TITLE
A question about EW-MHSA

### ISSUE THREAD

**Issue by peaes** [zhangzjn/EMO#14]
Amazing work!

I have a question about the code of EW-MHSA, how do you implement Q=K=X?

**Comment by zhangzjn** [comment]
@peaes 
We employ the standard multi-head self-attention mechanism, where 'q' and 'k' are obtained from the input 'x' through different linear layers, that is, 'q' is not equal to 'k'. Please refer to this [line](https://github.com/zhangzjn/EMO/blob/27d9b40fea9c2a12a2fe7acc51032184852a99d8/model/emo.py#L62) for more details.

**Comment by peaes** [comment]
thanks for your reply! I noticed your paper proposed the Improved EW-MHSA which Q=K=X. If I want to adopt this technique, how do I obtain 'q' and 'k'?

**Comment by peaes** [comment]
thanks for your reply! I noticed your paper proposed the Improved EW-MHSA which Q=K=X. If I want to adopt this technique, how do I obtain 'q' and 'k'?

**Comment by zhangzjn** [comment]
I know... The current code implementation is as per the paper, where Q=K=X. Generally, we assume that the inputs 'q' and 'k' for the MHSA operation are copies of 'x', which are then passed through different linear layers to obtain 'q1' and 'k1'', used to calculate the attention map. Perhaps what you are referring to as 'q' and 'k' are actually 'q1' and 'k1'.

**Comment by peaes** [comment]
I see. Thank you for your reply!
