### ISSUE TITLE
About the Inconsistency between the Implementation and the Paper. (e.g., the "attn_pre" setting.)

### ISSUE THREAD

**Issue by Leiyi-HU** [zhangzjn/EMO#15]
Sorry to bother you, I have seen the issue (https://github.com/zhangzjn/EMO/issues/9#issuecomment-1517183036), but I am still confused by the "attn_pre". As you describe in the paper, the qk and v will be multiplied after self.v() (e.g. set "attn_pre" to False), but you seem to set it to True. So I wonder which setting will produce the results you report in the published paper?

Thanks in advance!

**Comment by zhangzjn** [comment]
"attn_pre" is set to False by default for reproducing results in the paper.

**Comment by Leiyi-HU** [comment]
Thanks!
