### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by nikitml** [zhangzjn/EMO#2]
Hey! Interesting paper! Could you please share the source code or will you do it in the future? Thanks!

**Comment by zhangzjn** [comment]
Yes, we will definitely open source as soon as possible, currently in the company's internal review process. Thank you for your interest in our work~

**Comment by niujindacidian** [comment]
Waiting for the code

**Comment by chenjun2hao** [comment]
waiting for the code!!

**Comment by wangtiance** [comment]
Looking forward to the code!

**Comment by twmht** [comment]
+1

**Comment by zhangzjn** [comment]
Thanks for your attention to our work! Although the work is still under a review process, we have decided to release the code in advance for subsequent comparisons~🫶🏼
