### ISSUE TITLE
Which window partitioning strategy is used in EW-MHSA

### ISSUE THREAD

**Issue by IDKiro** [zhangzjn/EMO#3]
Very interesting work, and the final architecture is very elegant.
I would like to know which window partitioning strategy is used in EW-MHSA, the sliding (SASA) or the shifting (Swin)?

**Comment by zhangzjn** [comment]
We use the said sliding manner, i.e., Swin-like implementation without shifting, because the iRMB is designed to be as simple as possible for applications~ Thank you for your attention.

**Comment by IDKiro** [comment]
Understood, thank you for your reply.
