### ISSUE TITLE
Question about the FLOPs

### ISSUE THREAD

**Issue by liu-mengyang** [zhangzjn/EMO#5]
Amazing work and is inspired me a lot!

Can anyone help me more? I am confused about the calculation of FLOPs.

Suppose the shape of Q, K and V is `LxD`. I calculate FLOPs of Multi-Head Self-Attention without cosidering bias and the result is about `8xD^2xL+4xDxL^2`. I cannot get item with `L^2`.

**Comment by zhangzjn** [comment]
I'm sorry that I don't know where your question ($L^2$) corresponds to the paper, is it Table 2? I think your FLOPs calculation is fine.

**Comment by liu-mengyang** [comment]
I'm glad to see your reply!

It's Table 1. FLOPs of MHSA is calculated to `8xD^2xL+4xDxL^2+3xL^2`.

**Comment by zhangzjn** [comment]
We change Table 1 to Table 2 in the [updated version](https://arxiv.org/abs/2301.01146), which should be available after the update. For your question, we add FLOPs of Softmax operator (might be overlooked in some works), and this operation requires $power$, $multiplication$, and $addition$ operations on attention map with $L^2 \times L^2$, i.e., extra $3L^2$ FLOPs.

**Comment by liu-mengyang** [comment]
I understand, thanks!
