### ISSUE TITLE
Where can we find MetaMobile?

### ISSUE THREAD

**Issue by twmht** [zhangzjn/EMO#6]
https://github.com/zhangzjn/EMO/blob/main/resources/RetinaNet_EMO_1M/20221102_234131.log#L39

Where can we find the model?

**Comment by zhangzjn** [comment]
We employ "MetaMobile" in the logs during the experiments, which is "EMO".

**Comment by twmht** [comment]
@zhangzjn 

I see. But where are those keys https://github.com/zhangzjn/EMO/blob/main/resources/RetinaNet_EMO_1M/20221102_234131.log#L239 in EMO?

**Comment by zhangzjn** [comment]
@twmht No corresponding keys are used in our models, and we simply copy this config from [Swin-Transformer-Object-Detection/blob/c7b20110addde0f74b1fbf812b403d16a59a87a9/configs/swin/mask_rcnn_swin_small_patch4_window7_mstrain_480-800_adamw_3x_coco.py#L64](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/c7b20110addde0f74b1fbf812b403d16a59a87a9/configs/swin/mask_rcnn_swin_small_patch4_window7_mstrain_480-800_adamw_3x_coco.py#L64).
