### ISSUE TITLE
How to draw the Fig.7, the Diagonal similarity in S-3 with different components? 

### ISSUE THREAD

**Issue by Aiolus-X** [zhangzjn/EMO#8]
Hallo dear authors, could you please release the code for drawing the he Fig.7, the Diagonal similarity in S-3 with different components? And I am confused with the diagonal similarity, could you please explain it?

**Comment by zhangzjn** [comment]
@Aiolus-X 
```
x = torch.randn(1, C, H, W)
x = net.stage0(x)
x = net.stage0(x)
x = net.stage0(x)
B, C, H, W = x.shape
xs = []
for cnt in range(H):
    xs.append(x[0:1, :, cnt, cnt].unsqueeze(-1))
x = torch.cat(xs, dim=2)
sim = x.transpose(-2, -1) @ x
# sim = sim.softmax(dim=-1)
sim = (sim - sim.min()) / (sim.max() - sim.min())
```

**Comment by zhangzjn** [comment]
@Aiolus-X 
Given the feature map x $\in C\times H\times W$, we choose diagonal positions (_i.e._, $H$ positions and $H$ equals $W$ in general) to similarities among these positions. This explanatory experiment is to illustrate the effect of different structural designs on receptive fields. _E.g._, for a row, the greater similarity value with more regions indicates the larger valid receptive field of the model.

pseudo reference code as follows:
```
x = torch.randn(1, C, H, W)
x = net.stage0(x)
x = net.stage1(x)
x = net.stage2(x)
x = net.stage3(x)
B, C, H, W = x.shape
for cnt in range(H):
    xs.append(x[0:1, :, cnt, cnt].unsqueeze(-1))
x = torch.cat(xs, dim=2)
sim = x.transpose(-2, -1) @ x
sim = (sim - sim.min()) / (sim.max() - sim.min())

```

**Comment by Aiolus-X** [comment]
Thank you for your reply, however it is still confused to me that why the similarity matrix of these diagonal positions can reflect the receptive field? Are there existing any related works or references?

**Comment by zhangzjn** [comment]
@Aiolus-X 
We choose this method considering that the diagonal contains the farthest distance in the image. Also, you can try the manner of Fig.3 in [SegFormer](https://proceedings.neurips.cc/paper/2021/file/64f1f27bf1b4ec22924fd0acb550c235-Paper.pdf).
